### PR TITLE
Update Dockerfiles

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
In this Patch:
Change the source of the Docker to use openshift upstream base images

  - openshift/origin-release:golang-1.13
  - openshift/origin-base

Update Go version from 1.11 to 1.13 on Dockerfile.rhel7

Add GO111MODULE env var to Makefile. THis has been a known issue when
running on ci platforms using Go 1.12 or below.

### CODE REVIEW

**Comment by zvonkok** [comment]
@ArangoGutierrez Can you rename the Dockerfile for CI, `Dockerfile.ci` ? Thanks.

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez Can you rename the Dockerfile for CI, `Dockerfile.ci` ? Thanks.

25f3aeb

**Comment by ArangoGutierrez** [comment]
Waahooo 
it fixed the ci test
> https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/7203/rehearse-7203-pull-ci-openshift-psap-special-resource-operator-master-images/15

**Comment by ArangoGutierrez** [comment]
Bug 1813455

**Pull request merged**
