### PR TITLE
add 'sleep infinity' as one of the string to wait for

### PR DESCRIPTION
**Pull request by oatakan**
On one of the systems I test with, '+ sleep infinity' shows up as the last line in the log file as opposed to '+ wait':

`
Mounting NVIDIA driver rootfs...
+ mount --make-runbindable /sys
+ mount --make-private /sys
+ mkdir -p /run/nvidia/driver
+ mount --rbind / /run/nvidia/driver
+ _write_kernel_update_hook
+ '[' '!' -d /run/kernel/postinst.d ']'
+ return
+ '[' '!' -e /host/etc/containers/oci/hooks.d ']'
+ '[' -e /etc/containers/oci/hooks.d/oci-nvidia-hook.json ']'
+ cp /etc/containers/oci/hooks.d/oci-nvidia-hook.json /host/etc/containers/oci/hooks.d/.
+ echo 'Done, now waiting for signal'
Done, now waiting for signal
+ trap 'echo '\''Caught signal'\''; _shutdown && { kill 619190; exit 0; }' HUP INT QUIT PIPE TERM
+ trap - EXIT
+ true
+ wait 619190
+ sleep infinity
`
This PR adds another pattern (+ sleep infinity) to waitfor. I tested this with OpenShift 4.3. Not sure which branch to submit this against, so I picked master.

### CODE REVIEW

**Comment by zvonkok** [comment]
@oatakan This will be addressed with the new push to master. There will also be a Part2 of SRO describing this new feature.

**Comment by zvonkok** [comment]
@oatakan Can you please turn this into an issue for tracking?

**Comment by oatakan** [comment]
> @oatakan Can you please turn this into an issue for tracking?

done: https://github.com/openshift-psap/special-resource-operator/issues/18

**Pull request closed without merging**
