### PR TITLE
Release and versioning tunning 

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
small patch to align SRO repo with PSAP project defaults. 

Working towards upstreaming SRO.

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
@zvonkok maybe we need you to `/unhold` to release this PR?

**Comment by stevekuznetsov** [comment]
There's some internal error here in the merge bot, I'm looking

**Comment by stevekuznetsov** [comment]
Looks like you have configured pull requests in your repository to rebase when they merge, and this branch cannot be rebased. I would suggest not using that configuration.

**Comment by ArangoGutierrez** [comment]
@stevekuznetsov  landed again in `merge pool` even with a diff merge strategy

**Pull request merged**
