### PR TITLE
Adding monitoring support for SRO

### PR DESCRIPTION
**Pull request by zvonkok**
This is not well documented how to use monitoring and TLS with kube-rbac-proxy. Most of the steps in the monitoring guide are working but without kube-rbac-proxy. This setup here works also with kube-rbac-proxy. 

@dagrayvid PTAL we can scrape but we need some metrics created.

### CODE REVIEW

**Comment by zvonkok** [comment]
@dagrayvid I am good with it. Looking in how kustomize works it would be to much editing and moving files around to make it simpler. If you're good with it then do a lgtm. So you can concentrate on the metric.

**Comment by dagrayvid** [comment]
Yes, it seems good based on the testing I did. 

/lgtm

**Pull request merged**
